regions:
  900:
    nodes:
    - derpport: 7348
      hostname: derp.example.com
      name: 900a
      regionid: 900
      stunonly: false
      stunport: 7349
    - derpport: 443
      hostname: derp.example.com
      name: 900b
      regionid: 900
      stunonly: false
      stunpot: 3478
    regioncode: cn
    regionid: 900
    regionname: China
