http:
  routers:
    hs-rtr:
      rule: "Host(`{{env "CF_MASTER_DOMAIN"}}`)"
      entryPoints:
        - websecure
      middlewares:
        - ipwhitelist-cf
        - chain-common
          #- middlewares-authentik
      priority: 10
      service: hs-svc
    hs-ui-rtr:
      rule: "Host(`{{env "CF_MASTER_DOMAIN"}}`) && PathPrefix(`/web`)"
      entryPoints:
        - websecure
      middlewares:
        #- ipwhitelist-hs-internal
        - chain-common
        #priority: 15
      service: hs-ui-svc
